### ISSUE TITLE
Unnecessary package version dependency

### ISSUE THREAD

**Issue by mariaolaaksonen** [OpenGov/cython_hunspell#8]
When using the cyhunspell on Ubuntu 18.04 with libhunspell-dev package installed the following error is raised:
_ImportError: libhunspell-1.3.so.0: cannot open shared object file: No such file or directory_

The libhunspell package that is installed on Ubuntu 18.04 is version 1.6, so would it be possible to remove this kind of dependence on a certain package version? The cyhunspell itself seems to work with the newer libhunspell when the so.0 file is linked:
_sudo ln -s /usr/lib/x86_64-linux-gnu/libhunspell-1.6.so.0 /usr/lib/libhunspell-1.3.so.0_

**Comment by MSeal** [comment]
That sounds reasonable -- when we made the dependency most linux distros didn't bundle hunspell or had issues compiling later versions so we locked it down to avoid odd failures.

It appears it would just require changing https://github.com/OpenGov/cython_hunspell/blob/master/find_library.py#L238 and related functions to remove the 1.3.3 name association. Ideally it should add dependencies to libhunspell.so.0 and symlink to pre-existing installation or to the downloaded 1.3.3.

I won't be able to fix this for a bit as I'll be traveling in the near term. If you want to take a stab at making the changes to that file I can review when I'm back in town. Otherwise it may take me a little bit to get around to making and testing the change myself.
